* added case conversion functions

diff --git a/mulle-bashfunctions-env b/mulle-bashfunctions-env
--- a/mulle-bashfunctions-env
+++ b/mulle-bashfunctions-env
@@ -112,7 +112,7 @@ _find_local_library_path()
    then
       return 1
    fi
-   echo "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+   printf "%s\n" "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
 }
 
 
@@ -189,7 +189,7 @@ main()
          ;;
 
          --version)
-            echo "${MULLE_BASHFUNCTIONS_VERSION}"
+            printf "%s\n" "${MULLE_BASHFUNCTIONS_VERSION}"
             exit 0
          ;;
 
@@ -241,7 +241,7 @@ main()
       libexec-dir|library-path)
          if [ $# -eq 0 ]
          then
-            echo "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+            printf "%s\n" "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
             return 0
          fi
 
@@ -253,7 +253,7 @@ main()
       ;;
 
       version)
-         echo "${MULLE_BASHFUNCTIONS_VERSION}"
+         printf "%s\n" "${MULLE_BASHFUNCTIONS_VERSION}"
       ;;
 
       *)
@@ -435,7 +435,7 @@ _init()
 
       if [ -z "${_libexec_dir}" ]
       then
-         echo "$0 fatal Error: Could not find libexec (PWD: $PWD)" >&2
+         printf "%s\n" "$0 fatal Error: Could not find libexec (PWD: $PWD)" >&2
          exit 1
       fi
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${_libexec_dir}"
@@ -448,12 +448,12 @@ _init()
    then
       case "${1}" in
          libexec-dir|library-path)
-            echo "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+            printf "%s\n" "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
             exit 0
          ;;
 
          version)
-            echo "${MULLE_BASHFUNCTIONS_VERSION}"
+            printf "%s\n" "${MULLE_BASHFUNCTIONS_VERSION}"
             exit 0
          ;;
       esac
