* add physicalpath * speed up _make_tmp by using uuidgen

diff --git a/mulle-bashfunctions-env b/mulle-bashfunctions-env
--- a/mulle-bashfunctions-env
+++ b/mulle-bashfunctions-env
@@ -288,7 +288,7 @@ _init()
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`get_libexec_path "$0"`"
       if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
       then
-         echo "$0 fatal Error: Could not find libexec ($PWD)" >&2
+         echo "$0 fatal Error: Could not find libexec (PWD: $PWD)" >&2
          exit 1
       fi
    fi
