use _fatal now more often

diff --git a/mulle-bashfunctions-embed b/mulle-bashfunctions-embed
--- a/mulle-bashfunctions-embed
+++ b/mulle-bashfunctions-embed
@@ -202,6 +202,12 @@ main()
 #
 MULLE_EXECUTABLE="${MULLE_EXECUTABLE:-${BASH_SOURCE[0]:-${(%):-%x}}}"
 
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    #
@@ -231,7 +237,8 @@ _init()
          then
             if [ -z "`command -v "${executablepath}"`" ]
             then
-               echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
+               _fatal "mulle-bashfunctions-env not installed"
+
             else
                echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
             fi
@@ -240,8 +247,7 @@ _init()
       fi
 
       . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" ||
-         fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-   fi
+         _fatal "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"   fi
    
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
diff --git a/mulle-bashfunctions-env b/mulle-bashfunctions-env
--- a/mulle-bashfunctions-env
+++ b/mulle-bashfunctions-env
@@ -447,6 +447,12 @@ r_get_libexec_dir()
 #    other variables containing a filesystem path end with _FILE
 #    variables containing search paths end with _PATH
 #
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    #
@@ -473,8 +479,7 @@ _init()
 
       if [ -z "${RVAL}" ]
       then
-         printf "%s\n" "$0 fatal Error: Could not find libexec (PWD: $PWD)" >&2
-         exit 1
+         _fatal "Could not find libexec (PWD: $PWD)"
       fi
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${RVAL}"
    fi
@@ -498,11 +503,11 @@ _init()
    fi
 
    # shellcheck source=src/mulle-compatibility.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-compatibility.sh" || exit 1
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions-minimal.sh" || _fatal "loading mulle-bashfunctions-minimal.sh failed"
    # shellcheck source=src/mulle-logging.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh" || exit 1
+   include_mulle_bashfunctions_library "logging" || internal_fail "include mulle-version.sh fail"
    # shellcheck source=src/mulle-version.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-version.sh" || exit 1
+   include_mulle_bashfunctions_library "version" || internal_fail "include mulle-version.sh fail"
 
    shell_enable_pipefail
    shell_enable_extglob
diff --git a/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME b/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME
--- a/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME
+++ b/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME
@@ -191,6 +191,13 @@ main()
 #
 MULLE_EXECUTABLE="${MULLE_EXECUTABLE:-${BASH_SOURCE[0]:-${(%):-%x}}}"
 
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
+
 _init()
 {
    #
@@ -220,16 +227,16 @@ _init()
          then
             if [ -z "`command -v "${executablepath}"`" ]
             then
-               echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
+               _fatal "Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?"
             else
-               echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+               _fatal "Could not find libexec of mulle-bashfunctions-env ($PWD)"
             fi
             exit 1
          fi
       fi
 
       . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" ||
-         fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+         _fatal "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
    fi
    
    #  set -e # more pain then gain in the end
