* add a file to make mulle-bashfunctions embeddable in another script with the cost of adding 80k of script code * provide MULLE_USERNAME to shell scripts

diff --git a/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME b/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME
--- a/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME
+++ b/src/mulle-nat/file.sh/project/all/ONESHOT_FILENAME
@@ -185,6 +185,12 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
+
+#
+# set MULLE_EXECUTABLE here unless set already
+#
+MULLE_EXECUTABLE="${MULLE_EXECUTABLE:-${BASH_SOURCE[0]:-${(%):-%x}}}"
+
 _init()
 {
    #
@@ -205,24 +211,27 @@ _init()
       ;;
    esac
 
-   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   if [ -z "${MULLE_BASHGLOBAL_SH}" ]
    then
-      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
       if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
       then
-         if [ -z "`command -v "${executablepath}"`" ]
+         MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+         if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
-         else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            if [ -z "`command -v "${executablepath}"`" ]
+            then
+               echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
+            else
+               echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            fi
+            exit 1
          fi
-         exit 1
       fi
+
+      . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" ||
+         fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
    fi
-
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" ||
-      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
+   
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
@@ -232,10 +241,10 @@ _init()
    call_main "${<|ONESHOT_UPCASE_IDENTIFIER|>_FLAGS}" "$@"
 }
 
-#
-# set MULLE_EXECUTABLE here unless set already
-#
-MULLE_EXECUTABLE="${MULLE_EXECUTABLE:-${BASH_SOURCE[0]:-${(%):-%x}}}"
+##
+## Paste contents of mulle-bashfunctions-env-embed.sh here, if you don't 
+## want the dependency on mulle-bashfunctions.
+##
 
 _init "$@" # will call main indirectly via call_main
 
