* change filepath_concat to respect trailing / if part of filename * use $'\n' instead of literal linefeed * removed unused function write_protect_directory

diff --git a/src/mulle-nat/bash-script/project/all/ONE_SHOTNAME b/src/mulle-nat/bash-script/project/all/ONE_SHOTNAME
--- a/src/mulle-nat/bash-script/project/all/ONE_SHOTNAME
+++ b/src/mulle-nat/bash-script/project/all/ONE_SHOTNAME
@@ -149,7 +149,7 @@ _init()
       then
          if [ -z "`command -v "${executablepath}"`" ]
          then
-             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
             echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
          fi
